### ISSUE TITLE
add getlanguage

### ISSUE THREAD

**Issue by Feier68** [gigaclub/TranslationAPI#11]
für tab

**Comment by kevinxdev** [comment]
@Feier68 Das kannst du auch hiermit machen und brauchst du sowieso nur im Translation-Plugin. Eine API Implementierung ist unnötig. https://github.com/gigaclub/Translation-Plugin/blob/71e75ac623db26426f02e0c74175ccd68b2b3342/translation-paper/src/main/java/net/gigaclub/translation/data/Data.java#L26

**Comment by Feier68** [comment]
Ich schreib mal nen Tab für das translation  plugin das ist besser und übersichtlicher
Hab die Funktion nicht gesehen
